name: Full-year calendar
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics-plugin.svg
          base: ""
          plugin_isocalendar: yes
          plugin_stackoverflow: yes
          plugin_stackoverflow_user: 13382000
          plugin_stackoverflow_section: answers-top
          plugin_stackoverflow_limit: 5
          plugin_isocalendar_duration: full-year
